import { Suspense } from "react";
import { images } from "../constants/images";

export default function ImageGeneration() {
  return (
    <div className="w-full bg-neutral-50/75 px-5 py-20 flex flex-col items-center justify-center mt-10 gap-10">
      <div className="flex items-center justify-center gap-1 rounded-full py-1.5 px-5 bg-white border border-neutral-200 shadow-xs">
        <h5>Best text to image generator</h5>
        <img src={images.stars} alt="Create.ai" className="w-5" />
      </div>

      <div className="flex flex-col items-center justify-center">
        <h3 className="text-5xl font-semibold">Turn text to</h3>
        <h3 className="text-4xl font-semibold mt-5">
          <span className="text-sky-600 text-5xl ">image</span>, in seconds.
        </h3>
        <p className="mt-8 font-medium text-center">
          Unleash your creativity with AI. Turn your imagination into visual art
          in seconds - <br /> just type, and watch the magic happen
        </p>
        <button className="bg-gradient-to-r from-blue-400  to-rose-500 px-10 py-2 rounded-full text-white shadow-xs flex items-center justify-center gap-2 cursor-pointer mt-5">
          <h5 className="text-xs">Generate images</h5>
          <img src={images.stars} alt="Create.ai" className="w-5" />
        </button>
      </div>

      <div className="w-full flex flex-col items-start px-5 mt-70">
        <h4 className="text-2xl font-semibold">The Community Showcase</h4>
        <h5 className="text-xs text-gray-500 mt-2">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </h5>
        <Suspense>
        <div className="w-full mt-10 flex items-center justify-center gap-2">
          <div className="w-full h-150 overflow-hidden rounded-2xl">
            <img src={images.bird} alt="" className="w-full h-full rounded-2xl object-cover shadow-sm cursor-pointer" />
          </div>
          <div className="w-full h-96 flex flex-col items-center justify-center gap-2">
            <div className="w-full h-full flex items-center gap-2">
              <img src={images.black_dog} alt="" className="w-full h-75 rounded-2xl object-cover shadow-sm cursor-pointer" />
              <img src={images.lion_eye} alt="" className="w-full h-75 rounded-2xl object-cover shadow-sm cursor-pointer" />
            </div>
            <div className="w-full h-full flex items-center gap-2">
              <img src={images.lizard} alt="" className="w-full h-75 rounded-2xl object-cover shadow-sm cursor-pointer" />
              <img src={images.peacock} alt="" className="w-full h-75 rounded-2xl object-cover shadow-sm cursor-pointer" />
            </div>
          </div>
        </div>
        </Suspense>
      </div>
    </div>
  );
}
